if(NOT DEFINED LOCKDC_EXTERNAL_ROOT OR LOCKDC_EXTERNAL_ROOT STREQUAL "")
  message(FATAL_ERROR "LOCKDC_EXTERNAL_ROOT is required")
endif()

function(assert_exists path description)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "missing ${description}: ${path}")
  endif()
endfunction()

function(assert_not_exists path description)
  if(EXISTS "${path}" OR IS_SYMLINK "${path}")
    message(FATAL_ERROR "unexpected ${description}: ${path}")
  endif()
endfunction()

assert_exists("${LOCKDC_EXTERNAL_ROOT}/curl/install/include/curl/curl.h" "curl public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/curl/install/lib/libcurl.a" "curl static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/curl/install/lib/libcurl.so" "curl shared library")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/curl/install/bin" "curl install bin directory")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/curl/install/lib/pkgconfig" "curl pkg-config metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/curl/install/lib/cmake" "curl CMake metadata")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/include/openssl/ssl.h" "OpenSSL public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/libssl.a" "OpenSSL ssl static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/libcrypto.a" "OpenSSL crypto static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/libssl.so" "OpenSSL ssl shared library")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/libcrypto.so" "OpenSSL crypto shared library")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/bin" "OpenSSL install bin directory")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/pkgconfig" "OpenSSL pkg-config metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/cmake" "OpenSSL CMake metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/engines-3" "OpenSSL engines directory")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/ossl-modules" "OpenSSL provider modules directory")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/libssh2/install/include/libssh2.h" "libssh2 public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/libssh2/install/lib/libssh2.a" "libssh2 static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/libssh2/install/lib/libssh2.so" "libssh2 shared library")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/libssh2/install/lib/pkgconfig" "libssh2 pkg-config metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/libssh2/install/lib/cmake" "libssh2 CMake metadata")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install/include/nghttp2/nghttp2.h" "nghttp2 public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install/lib/libnghttp2.a" "nghttp2 static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install/lib/libnghttp2.so" "nghttp2 shared library")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install/lib/pkgconfig" "nghttp2 pkg-config metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install/lib/libnghttp2.la" "nghttp2 libtool archive")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/zlib/install/include/zlib.h" "zlib public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/zlib/install/lib/libz.a" "zlib static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/zlib/install/lib/libz.so" "zlib shared library")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/zlib/install/lib/pkgconfig" "zlib pkg-config metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/zlib/install/lib/cmake" "zlib CMake metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/zlib/install/share/man" "zlib man pages")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/lonejson/install/include/lonejson.h" "lonejson public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/lonejson/install/lib/liblonejson.a" "lonejson static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/lonejson/install/lib/liblonejson.so" "lonejson shared library")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/lonejson/install/lib/pkgconfig/lonejson.pc" "lonejson pkg-config metadata")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/lonejson/install/lib/cmake/lonejson/lonejsonConfig.cmake" "lonejson CMake metadata")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/lonejson/install/lib/cmake/lonejson/lonejsonConfigVersion.cmake" "lonejson CMake version metadata")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/pslog/install/include/pslog.h" "pslog public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/pslog/install/lib/libpslog.a" "pslog static archive")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/pslog/install/lib/libpslog.so" "pslog shared library")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/pslog/install/lib/pkgconfig/pslog.pc" "pslog pkg-config metadata")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/pslog/install/lib/cmake/pslog/pslogConfig.cmake" "pslog CMake metadata")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/pslog/install/lib/cmake/pslog/pslogConfigVersion.cmake" "pslog CMake version metadata")

assert_exists("${LOCKDC_EXTERNAL_ROOT}/cmocka/install/include/cmocka.h" "cmocka public header")
assert_exists("${LOCKDC_EXTERNAL_ROOT}/cmocka/install/lib/libcmocka.a" "cmocka static archive")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/cmocka/install/lib/pkgconfig" "cmocka pkg-config metadata")
assert_not_exists("${LOCKDC_EXTERNAL_ROOT}/cmocka/install/lib/cmake" "cmocka CMake metadata")
