set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

include("${CMAKE_CURRENT_LIST_DIR}/../CpktBootlinToolchain.cmake")
cpkt_configure_bootlin_toolchain(armhf-linux-musl)

set(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/qemu-arm;-L;${CMAKE_SYSROOT} CACHE STRING "")

set(LOCKDC_TARGET_ARCH armhf CACHE STRING "" FORCE)
set(LOCKDC_TARGET_OS linux CACHE STRING "" FORCE)
set(LOCKDC_TARGET_LIBC musl CACHE STRING "" FORCE)
