set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER /usr/bin/cc CACHE FILEPATH "")
set(CMAKE_AR /usr/bin/ar CACHE FILEPATH "")
set(CMAKE_RANLIB /usr/bin/ranlib CACHE FILEPATH "")

set(LOCKDC_TARGET_ARCH x86_64 CACHE STRING "" FORCE)
set(LOCKDC_TARGET_OS linux CACHE STRING "" FORCE)
set(LOCKDC_TARGET_LIBC gnu CACHE STRING "" FORCE)
