#ifndef LC_POUCH_FORMAT_H
#define LC_POUCH_FORMAT_H

#define LC_POUCH_LAYOUT_NAME "pouch-segmented"
#define LC_POUCH_LAYOUT_VERSION 1UL
#define LC_POUCH_DEFAULT_SEGMENT_TARGET_BYTES (64UL * 1024UL * 1024UL)
#define LC_POUCH_DEFAULT_COMPACTION_MIN_SEGMENT_COUNT 4UL
#define LC_POUCH_DEFAULT_COMPACTION_MIN_RECLAIMABLE_BYTES                      \
  (16UL * 1024UL * 1024UL)
#define LC_POUCH_DEFAULT_COMPACTION_DELETE_GRACE_SECONDS (15UL * 60UL)

#endif
