#ifndef LC_POUCH_FORMAT_H
#define LC_POUCH_FORMAT_H

#define LC_POUCH_LAYOUT_NAME "pouch-segmented"
#define LC_POUCH_LAYOUT_VERSION 1UL
#define LC_POUCH_DEFAULT_SEGMENT_TARGET_BYTES (64UL * 1024UL * 1024UL)
#define LC_POUCH_DEFAULT_COMPACTION_MIN_SEGMENT_COUNT 2UL
#define LC_POUCH_DEFAULT_COMPACTION_MIN_RECLAIMABLE_BYTES                      \
  (64UL * 1024UL * 1024UL)
#define LC_POUCH_DEFAULT_COMPACTION_INTERVAL_SECONDS (30UL * 60UL)
#define LC_POUCH_DEFAULT_COMPACTION_DELETE_GRACE_SECONDS (15UL * 60UL)
#define LC_POUCH_DEFAULT_COMPACTION_MAX_IO_BYTES_PER_SEC                      \
  (8UL * 1024UL * 1024UL)
#define LC_POUCH_DEFAULT_JANITOR_INTERVAL_SECONDS (60UL * 60UL)

#endif
