if(NOT DEFINED LOCKDC_EXTERNAL_ROOT OR LOCKDC_EXTERNAL_ROOT STREQUAL "")
  message(FATAL_ERROR "LOCKDC_EXTERNAL_ROOT is required")
endif()

function(lockdc_remove_if_exists path)
  if(EXISTS "${path}" OR IS_SYMLINK "${path}")
    file(REMOVE_RECURSE "${path}")
  endif()
endfunction()

function(lockdc_prune_doc_tree install_root)
  set(doc_root "${install_root}/share/doc")
  if(NOT EXISTS "${doc_root}")
    return()
  endif()

  file(GLOB doc_entries RELATIVE "${doc_root}" "${doc_root}/*")
  foreach(doc_entry IN LISTS doc_entries)
    if(NOT doc_entry STREQUAL "liblockdc-third-party")
      file(REMOVE_RECURSE "${doc_root}/${doc_entry}")
    endif()
  endforeach()
endfunction()

function(lockdc_prune_install_tree install_root)
  if(NOT EXISTS "${install_root}")
    return()
  endif()

  lockdc_remove_if_exists("${install_root}/bin")
  lockdc_remove_if_exists("${install_root}/lib/pkgconfig")
  lockdc_remove_if_exists("${install_root}/lib/cmake")
  lockdc_remove_if_exists("${install_root}/share/man")
  lockdc_prune_doc_tree("${install_root}")
endfunction()

lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/curl/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/libssh2/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/zlib/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/openssl/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/pslog/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/cmocka/install")
lockdc_prune_install_tree("${LOCKDC_EXTERNAL_ROOT}/lonejson/install")

lockdc_remove_if_exists("${LOCKDC_EXTERNAL_ROOT}/nghttp2/install/lib/libnghttp2.la")
lockdc_remove_if_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/engines-3")
lockdc_remove_if_exists("${LOCKDC_EXTERNAL_ROOT}/openssl/install/lib/ossl-modules")
